### PR TITLE
[WIP] Fix the __GLASGOW_HASKELL__ comparison

### PR DESCRIPTION
**Pull request by ggreif**
### DON'T MERGE YET, MORE TO COME

for older than v8.4.x GHC

See: https://ghc.haskell.org/trac/ghc/ticket/14924

### CODE REVIEW

**Comment by monoidal** [comment]
There are three more (`git grep GLASGOW_HASKELL*840`)

**Comment by monoidal** [comment]
Hi, can I take this over? As far as I can tell it's just 4 lines of code, this can be done quickly.

**Comment by ggreif** [comment]
Yeah, go for it +1

**Comment by monoidal** [comment]
Done in 97826e343c4.

**Comment by ggreif** [comment]
Thanks @monoidal !

**Pull request closed without merging**
