### PR TITLE
llvm-targets: Add armv6l-unknown-linux-gnueabihf and armv7l-unknown-l…

### PR DESCRIPTION
**Pull request by ggardet**
…inux-gnueabihf

### CODE REVIEW

**Comment by angerman** [comment]
LGTM.

**Comment by bgamari** [comment]
Thanks!

**Comment by bgamari** [comment]
Merged with e4003b6dc6a84d870116de9f47057c15b1576f36

**Comment by angerman** [comment]
@vdukhovni feel fee to open a PR on github, or Diff on phabricator (https://phabricator.haskell.org/) for this. I'm sure we can add more targets.

**Pull request closed without merging**
