### PR TITLE
add Unit# and Unit to PrelInfo.ghcPrimExports

### PR DESCRIPTION
**Pull request by chessai**
addresses https://ghc.haskell.org/trac/ghc/ticket/14673.

### CODE REVIEW

**Comment by bgamari** [comment]
Thanks, let's make sure we are satisfied with the name before moving ahead with this though.

**Comment by chessai** [comment]
@bgamari I know that none of you, @andrewthad, @taktoa, or myself are satisfied with the name Unit and Unit#.

**Comment by iamrecursion** [comment]
Some discussion on the linked ticket about possible names.

**Comment by andrewthad** [comment]
@chessai The names `Solo`/`Solo#` have been decided on. Would you be able to update this?

**Comment by treeowl** [comment]
What's the status of this? It looks like it's still missing documentation and a changelog entry.

**Comment by chessai** [comment]
What sort of documentation? Also, to which changelog? ghc-prim's?

**Comment by treeowl** [comment]
If `ghc-prim` has a changelog, then that. Regardless, it needs to go in the main GHC changelog. It should be documented in the user's guide, in the section on unboxed tuples.

**Comment by treeowl** [comment]
Several pieces of this still don't seem to work. I've rebased and fixed some of the issues in [D4720](https://phabricator.haskell.org/D4720), but it appears that the `Solo#` type constructor still isn't actually available to Haskell code. @bgamari, can you advise on what may be missing there?

**Comment by chessai** [comment]
Would it be preferable for me to get set up with Phabricator and continue there, @treeowl @bgamari ?

**Comment by treeowl** [comment]
@chessai, we do tend to prefer that for anything that's not really small, but it's up to you; I know this one is already well on the way. Regardless, I suggest you start from [my branch](https://github.com/treeowl/ghc/tree/solo-type), which is rebased and has some of the issues fixed.

**Pull request closed without merging**
