### PR TITLE
Increase the amount of parallelism in circleci.

### PR DESCRIPTION
**Pull request by facundominguez**
This almost halves the time of the build. For some reason circleci was not configured to use all the 8 cpus of the xlarge containers.
https://circleci.com/gh/tweag/ghc/205

### CODE REVIEW

**Comment by mboes** [comment]
Has using the c4.xlarge EC2 instance type been enabled for this repository? It takes making a special request to CircleCI support. See earlier discussion about this: https://mail.haskell.org/pipermail/ghc-devs/2017-September/014740.html

**Comment by facundominguez** [comment]
Given the duration of `validate-x86_64-linux-llvm` for this PR it does look like `xlarge` is enabled.

**Comment by facundominguez** [comment]
Submitted as a revision in phabricator too: https://phabricator.haskell.org/D4415

**Comment by facundominguez** [comment]
Merged the phabricator revision.

**Pull request closed without merging**
