### PR TITLE
Fix stat failures and correct expected stderr output of T11489

### PR DESCRIPTION
**Pull request by mrkkrp**
Most of the stat failures were marked as “too good”, so this commit adjusts
them to avoid failures in ‘linux’ and ‘darwin’ Circle CI jobs. One stat test
had a deviation 5.1% with allowed derivation +-5%. At the same time the test
has allowed deviation +-10% for 32 bit platforms, so I guess specifying the
same deviation for 64 bit platforms is not a sin.

“Can't open profiling report file T11489” is not what we get in ‘linux’ job,
stderr output for that test is empty there, and I think it's the correct
behaviour. It seems unlikely that “Can't open profiling report file T11489”
is really the expected output of that test, it's probably a bug in the test
suite.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Related ticket: https://ghc.haskell.org/trac/ghc/ticket/14823#ticket

**Comment by mrkkrp** [comment]
So can we merge this or some adjustment is needed?

**Comment by bgamari** [comment]
Alright, let's merge this.

**Comment by bgamari** [comment]
Actually, on second thought it's not clear to me that this is needed:

 * the performance tests are moot since I've now disabled performance tests in preparation for #12758.
 * the change to #11489 is incorrect; as noted in #14706 this test is expected to fail.
 * `scc001` doesn't reliably fail so marking it as `expect_broken` would produce break some environments. Perhaps we should instead just mark it as `skip` with a comment.

**Comment by facundominguez** [comment]
> the change to #11489 is incorrect; as noted in #14706 this test is expected to fail.

Perhaps it is easy to have CI jobs create a test user and build and test with it.

**Comment by bgamari** [comment]
> Perhaps it is easy to have CI jobs create a test user and build and test with it, so we don't use root.

See [D4360](https://phabricator.haskell.org/D4360) for my attempt at fixing this. 

Note that I have a variety of patches in flight fixing various aspects of the CI scheme:

 * D4354
 * D4360
 * D4411
 * D4425

Unfortunately I'm very much lacking the bandwidth to push them through at the moment. Any help you could offer would be greatly appreciated.

**Comment by mrkkrp** [comment]
@bgamari OK, I started working on D4360. However it fails with:

```
Build-agent version 0.0.4710-44beb0a (2018-02-27T20:05:34+0000)
Starting container ghcci:x86_64-linux
  image cache not found on this host, downloading ghcci:x86_64-linux
Error response from daemon: repository ghcci not found: does not exist or no pull access
```

In the comments I see that `dfeuer` asked about the new images and you pointed out that the images are in `.circleci/images`. But I only see the old images there. Maybe you forgot to commit them? Or should we create the images?

**Comment by mrkkrp** [comment]
Regarding [D4411](https://phabricator.haskell.org/D4411): the patch adds a build with `devel2` flavor. The changes however appear to be already present in current master. Should I drop this patch from consideration? Should it be closed on Phabricator?

**Pull request closed without merging**
