### PR TITLE
Add missing initial version for extension doc.

### PR DESCRIPTION
**Pull request by superfunc**
Small bit I noticed missing when perusing some docs this morning.

### CODE REVIEW

**Comment by bgamari** [comment]
This is missing a colon after `:since` but I can fix this when I merge it.

**Comment by bgamari** [comment]
Thanks!

**Comment by superfunc** [comment]
Doh! Sorry about that. Thanks!

**Comment by superfunc** [comment]
I got it updated, thanks for letting me know, should be good to go now.

**Comment by bgamari** [comment]
Merged.

**Pull request closed without merging**
