### PR TITLE
Add Wredundant-constraints to Wall exceptions

### PR DESCRIPTION
**Pull request by siddhanathan**
In light of https://ghc.haskell.org/trac/ghc/ticket/10635

### CODE REVIEW

**Comment by mpickering** [comment]
The last commit in that thread says that it was removed from `-Wall`.

**Comment by siddhanathan** [comment]
> The last commit in that thread says that it was removed from -Wall.

Yes, this is a documentation change only.

**Comment by mpickering** [comment]
I see now, this is a list of exceptions which are NOT enabled by `-Wall`.

**Comment by int-index** [comment]
The name of the PR is misleading, you're adding `-Wredundant-constraints` into the list of warnings *not* enabled by `-Wall`.

But the patch appears correct.

**Comment by nomeata** [comment]
Fixed the commit message, pushed as 5ce39f6.

**Pull request closed without merging**
