### PR TITLE
Quick AppVeyor build

### PR DESCRIPTION
**Pull request by mrkkrp**
This build succeeds and fits into the 90 minutes window.

### CODE REVIEW

**Comment by mrkkrp** [comment]
I don't understand why AppVeyor build failed. Maybe you only have 60 minutes there? I think I saw an email where @bgamari said that we have 90 minutes now...

**Comment by bgamari** [comment]
Hmm, it seems that the build was run against my personal account, not the [GHCAppveyor](https://ci.appveyor.com/project/GHCAppveyor/ghc) account that has the lifted build time limit. Actually, it appears that the build was indeed run in the [GHCAppveyor](https://ci.appveyor.com/project/GHCAppveyor/ghc/build/86) account but for some reason GHC is only showing the result from the build in my personal build.

**Comment by bgamari** [comment]
I have delete the Appveyor project corresponding to `ghc/ghc` in my personal Appveyor account. Can you push again to verify this>

**Comment by facundominguez** [comment]
Rebased master.

**Comment by mrkkrp** [comment]
Still hits the 1h limit...

**Comment by bgamari** [comment]
I have [pinged](https://github.com/appveyor/ci/issues/517#issuecomment-368329008) the Appveyor folks about this.

**Comment by bgamari** [comment]
It sounds like the issue was a mistake on Appveyor's end which should be fixed now. Perhaps try pushing again.

**Comment by mrkkrp** [comment]
AppVeyor is finally green.

**Comment by bgamari** [comment]
Lovely, let's merge this.

**Comment by bgamari** [comment]
Thanks @mrkkrp !

**Pull request merged**
