### PR TITLE
Add missing -Wdeprecations flag to the users guide (Trac #12379)

### PR DESCRIPTION
**Pull request by erdeszt**
Based on the conversation in [Trac](https://ghc.haskell.org/trac/ghc/ticket/12379) I've added the missing the flag. Only changing the docs so I hope it can get through here.

### CODE REVIEW

**Comment by bgamari** [comment]
Thanks for this, this looks great! I'll merge shortly.

**Comment by bgamari** [comment]
Merged.

**Comment by erdeszt** [comment]
@bgamari What should I do about the ticket? The wiki says I should add the differential revision but it looks like this got merged through diffusion.

**Comment by bgamari** [comment]
@erdeszt, don't worry, I will take care of it once I merge it to `ghc-8.2`.

**Pull request closed without merging**
