### PR TITLE
base: Misc haddock fixes

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
I have opened https://github.com/haskell/haddock/issues/951 to make it possible to link operators with the `'(+)'` syntax.

**Comment by sjakobi** [comment]
> Should we not just wait until that PR is merged?

I'm afraid that's just a feature request, not a PR. :/

**Comment by bgamari** [comment]
Alright then. Let's go ahead and merge this then.

**Comment by bgamari** [comment]
Merged with c088137949bd69ee463c08a0d221517bc5108945.

**Pull request closed without merging**
